{
 "title": "Bucket Overview",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-bucket"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_ALERTMANAGER_API", "query": "marcusolsson-json-datasource" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "query_result(max by (cluster_uuid) (multimanager_cluster_checker_status{cluster_name=${cluster:doublequote}}))"
    }
   },
   {
    "name": "bucket",
    "query": {
     "query": "query_result(multimanager_bucket_checker_status{cluster_name=${cluster:doublequote}})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket Health Issues",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\",bucket=\"$bucket\"} >= 0"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$[*].labels.health_check_id", "name": "id" },
      { "jsonPath": "$[*].labels.health_check_name", "language": "jsonpath", "name": "name" },
      {
       "jsonPath": "[$.labels.severity ~> $map(function($a) {\n$a = \"critical\" ? 30 :\n$a = \"warning\" ? 20 :\n$a = \"info\" ? 10 : -1\n})]",
       "language": "jsonata",
       "name": "Value"
      }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=job=~\"couchbase_(prometheus|fluent_bit)$\"&filter=kind=bucket&filter=cluster=${cluster:querystring}&filter=bucket=${bucket:querystring}"
    }
   ]
  },
  {
   "title": "Active Resident Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kv_vb_perc_mem_resident_ratio{bucket=\"$bucket\",cluster=\"$cluster\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kv_mem_used_bytes{cluster=\"$cluster\",bucket=\"$bucket\"})",
     "legendFormat": "In Memory"
    },
    {
     "expr": "sum (couch_docs_actual_disk_size{cluster=\"$cluster\",bucket=\"$bucket\"})",
     "legendFormat": "On Disk"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (scope, collection) (kv_collection_data_size_bytes{cluster=\"$cluster\",bucket=\"$bucket\"})"
    },
    {
     "expr": "sum by (scope, collection) (kv_collection_item_count{cluster=\"$cluster\",bucket=\"$bucket\"})"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (op) (rate(kv_ops{cluster=`$cluster`,bucket=`$bucket`}[$__rate_interval]))",
     "legendFormat": "{{ op }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (kv_ep_mem_low_wat{cluster=\"$cluster\",bucket=\"$bucket\"})",
     "legendFormat": "Low Water Mark"
    },
    {
     "expr": "avg (kv_ep_mem_high_wat{cluster=\"$cluster\",bucket=\"$bucket\"})",
     "legendFormat": "High Water Mark"
    },
    {
     "expr": "kv_mem_used_bytes{cluster=\"$cluster\",bucket=\"$bucket\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance) (kv_ep_diskqueue_items{cluster=`$cluster`,bucket=`$bucket`})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "90th Percentile Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, irate(kv_cmd_duration_seconds_bucket{opcode=\"GET\",bucket=\"$bucket\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}