{
 "title": "Eventing Service",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "couchbase-service-eventing"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "function",
    "label": "Function",
    "query": {
     "query": "query_result(present_over_time(eventing_on_update_success{cluster=`$cluster`}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of functions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by (functionName) (eventing_agg_queue_size{cluster=`$cluster`}))"
    }
   ]
  },
  {
   "title": "Total number of failed function runs",
   "type": "stat",
   "description": "This is in the past time range, i.e., the value set in the top-right corner of \"Last X time unit\" (defaults to 30 minutes).",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(eventing_on_update_failure{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__range])))",
     "legendFormat": "Update"
    },
    {
     "expr": "round(sum(increase(eventing_on_delete_failure{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__range])))",
     "legendFormat": "Delete"
    },
    {
     "expr": "round(sum(increase(eventing_timeout_count{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__range])))",
     "legendFormat": "Timeout"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (functionName) (eventing_agg_queue_size{cluster=`$cluster`,functionName=~`^${function:regex}$`})",
     "legendFormat": "{{ functionName }}"
    }
   ]
  },
  {
   "title": "Total Queue Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (functionName) (eventing_agg_queue_memory{cluster=`$cluster`,functionName=~`^${function:regex}$`})",
     "legendFormat": "{{ functionName }}"
    }
   ]
  },
  {
   "title": "Successful Function Runs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(eventing_on_update_success{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__rate_interval])",
     "legendFormat": "{{functionName}} Update"
    },
    {
     "expr": "irate(eventing_on_delete_success{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__rate_interval])",
     "legendFormat": "{{functionName}} Delete"
    }
   ]
  },
  {
   "title": "Failed Function Runs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(eventing_on_update_failure{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__rate_interval])",
     "legendFormat": "{{functionName}} Update"
    },
    {
     "expr": "irate(eventing_on_delete_failure{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__rate_interval])",
     "legendFormat": "{{functionName}} Delete"
    },
    {
     "expr": "irate(eventing_timeout_count{cluster=`$cluster`,functionName=~`^${function:regex}$`}[$__rate_interval])",
     "legendFormat": "{{functionName}} Timeout"
    }
   ]
  }
 ]
}