{
 "title": "Single Cluster Overview",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_ALERTMANAGER_API", "query": "marcusolsson-json-datasource" },
   {
    "name": "DS_COUCHBASE_CLUSTER_MONITOR_API",
    "query": "marcusolsson-json-datasource"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "multimanager_cluster_checker_status{cluster_name=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview - at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$cluster", "language": "jsonata", "name": "Cluster Name", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$count($.nodes_summary[*])", "language": "jsonata", "name": "Number of nodes" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "description": "Scroll down to \"Health Status\" to see the alerts.",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} == 30) or absent(count(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} == 30)) - 1) + \nscalar(count(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} == 30) or absent(count(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} == 30)) - 1) + \nscalar(count(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} == 30) or absent(count(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} == 30)) - 1)",
     "legendFormat": "critical_alerts"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$count($)", "language": "jsonata" }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=job=~\"couchbase_(prometheus|fluent_bit)$\"&filter=cluster=\"${cluster:querystring}\"&filter=severity=critical"
    }
   ]
  },
  {
   "title": "Running Services (clickable!)",
   "type": "stat",
   "description": "Click on each service to be taken to its dashboard page.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"kv\"}) ~> $count",
       "language": "jsonata",
       "name": "Data"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"index\"}) ~> $count",
       "language": "jsonata",
       "name": "Index"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"fts\"}) ~> $count",
       "language": "jsonata",
       "name": "Search"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"n1ql\"}) ~> $count",
       "language": "jsonata",
       "name": "Query"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"eventing\"}) ~> $count",
       "language": "jsonata",
       "name": "Eventing"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"cbas\"}) ~> $count",
       "language": "jsonata",
       "name": "Analytics"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"backup\"}) ~> $count",
       "language": "jsonata",
       "name": "Backup"
      },
      { "jsonPath": "0", "language": "jsonata", "name": "..." }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")})",
       "language": "jsonata",
       "name": "Version",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$count($.buckets_summary[*])", "language": "jsonata", "name": "Number of buckets" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "description": "Scroll down to \"Health Status\" to see the warnings.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} == 20) or absent(count(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} == 20)) - 1) + \nscalar(count(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} == 20) or absent(count(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} == 20)) - 1) + \nscalar(count(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} == 20) or absent(count(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} == 20)) - 1)",
     "legendFormat": "warnings"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$count($)", "language": "jsonata" }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=job=~\"couchbase_(prometheus|fluent_bit)$\"&filter=cluster=\"${cluster:querystring}\"&filter=severity=warning"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "description": "Scroll down to \"Health Status\" for more information.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} == 10) or absent(count(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} == 10)) - 1) + \nscalar(count(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} == 10) or absent(count(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} == 10)) - 1) + \nscalar(count(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} == 10) or absent(count(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} == 10)) - 1)",
     "legendFormat": "critical_alerts"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$count($)" }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=job=~\"couchbase_(prometheus|fluent_bit)$\"&filter=severity=info"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "Couchbase recommends a minimum of 8 CPUs, 8GB RAM, and keeping RAM usage below 80%.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*].host, function($h) {\n    $replace(\n      $replace($h, /:\\d+$/, \"\")\n    , /https?:\\/\\//, \"\")\n})",
       "language": "jsonata",
       "name": "Node"
      },
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")})",
       "language": "jsonata",
       "name": "Version"
      },
      { "jsonPath": "$.nodes_summary[*].os", "language": "jsonpath", "name": "Operating System" },
      {
       "jsonPath": "$map($.nodes_summary[*], function($node) {\n  $join($sort($map($node.services, function ($svc) {\n    $svc = \"cbas\" ? \"Analytics\" :\n    $svc = \"n1ql\" ? \"Query\" :\n    $svc = \"eventing\" ? \"Eventing\" :\n    $svc = \"index\" ? \"Index\" :\n    $svc = \"fts\" ? \"Search\" :\n    $svc = \"kv\" ? \"Data\" :\n    $svc = \"backup\" ? \"Backup\" : $svc\n  })), \", \")\n})",
       "language": "jsonata",
       "name": "Services"
      },
      {
       "jsonPath": "$.nodes_summary[*] ~> $map(function($node) {\n  $node.status = \"healthy\"\n  ? $node.cluster_membership\n  : $node.status\n})",
       "language": "jsonata",
       "name": "State"
      },
      {
       "jsonPath": "$map($.nodes_summary, function($n) {$n.cpuCount ? $n.cpuCount : \"(unknown)\"})",
       "language": "jsonata",
       "name": "CPUs"
      },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  $node.mem_total ? $formatNumber($round($node.mem_total / 1024 / 1024 / 1024), \"####;(#0.00)\") : \"(unknown)\"\n})",
       "language": "jsonata",
       "name": "Total RAM"
      },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  ($node.mem_free and $node.mem_total) ? $round((1 - ($node.mem_free / $node.mem_total)) * 100, 2) : \"(unknown)\"\n})",
       "language": "jsonata",
       "name": "RAM Usage"
      },
      { "jsonPath": "$.nodes_summary[*].node_uuid", "language": "jsonpath", "name": "uuid" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Dataset",
   "type": "table",
   "description": "Couchbase recommends at least one replica, keeping Resident Ratio above 10%, and Quota used below 80%.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.buckets_summary[*].name", "name": "bucket" },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $formatNumber($b.items, \"#,###\")\n})",
       "language": "jsonata",
       "name": "Items Stored"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $b.quota / 1024 / 1024 / 1024\n})",
       "language": "jsonata",
       "name": "Quota"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $round($b.quota_used, 2)\n})",
       "language": "jsonata",
       "name": "Quota Used",
       "type": "number"
      },
      {
       "jsonPath": "$.buckets_summary[*].num_replicas",
       "language": "jsonata",
       "name": "Replicas"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "count by (bucket) (index_items_count{cluster=`$cluster`}) or max by (bucket) (clamp_max(kv_ops{cluster=`$cluster`}, 0))",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "expr": "min by (bucket) (kv_vb_perc_mem_resident_ratio{cluster=`$cluster`,state=\"active\"})"
    }
   ]
  },
  { "title": "Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Cluster Check Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$[*].labels.health_check_id", "name": "id" },
      { "jsonPath": "$[*].labels.health_check_name", "language": "jsonpath", "name": "name" },
      {
       "jsonPath": "[$.labels.severity ~> $map(function($a) {\n$a = \"critical\" ? 30 :\n$a = \"warning\" ? 20 :\n$a = \"info\" ? 10 : -1\n})]\n",
       "language": "jsonata",
       "name": "Value"
      }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=cluster=${cluster:querystring}&filter=kind=cluster&filter=job=~\"couchbase_(prometheus|fluent_bit)$\""
    }
   ]
  },
  {
   "title": "Node Check Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$[*].labels.health_check_id", "name": "id" },
      { "jsonPath": "$[*].labels.health_check_name", "language": "jsonpath", "name": "name" },
      { "jsonPath": "$[*].labels.node", "language": "jsonpath", "name": "node_name" },
      {
       "jsonPath": "[$.labels.severity ~> $map(function($a) {\n$a = \"critical\" ? 30 :\n$a = \"warning\" ? 20 :\n$a = \"info\" ? 10 : -1\n})]",
       "language": "jsonata",
       "name": "Value"
      }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=cluster=${cluster:querystring}&filter=kind=node&filter=job=~\"couchbase_(prometheus|fluent_bit)$\""
    }
   ]
  },
  {
   "title": "Bucket Check Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$[*].labels.health_check_id", "name": "id" },
      { "jsonPath": "$[*].labels.health_check_name", "language": "jsonpath", "name": "name" },
      { "jsonPath": "$[*].labels.bucket", "language": "jsonpath", "name": "bucket" },
      {
       "jsonPath": "[$.labels.severity ~> $map(function($a) {\n$a = \"critical\" ? 30 :\n$a = \"warning\" ? 20 :\n$a = \"info\" ? 10 : -1\n})]\n",
       "language": "jsonata",
       "name": "Value",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=cluster=${cluster:querystring}&filter=kind=bucket&filter=job=~\"couchbase_(prometheus|fluent_bit)$\""
    }
   ]
  },
  { "title": "System resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_utilization_rate{cluster=${cluster:doublequote}}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_mem_actual_used{cluster=${cluster:doublequote}} / \nsys_mem_total{cluster=${cluster:doublequote}}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "KPIs - Data Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Reads per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ops{cluster=\"$cluster\",op=\"get\"}[$__rate_interval]))",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.50, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\"}[$__rate_interval]))))",
     "legendFormat": "50th percentile (avg)"
    },
    {
     "expr": "max(histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\"}[$__rate_interval]))))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(histogram_quantile(0.999, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\"}[$__rate_interval]))))",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Writes per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ops{cluster=\"$cluster\",op=\"set\"}[$__rate_interval]))",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.50, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\"}[$__rate_interval]))))",
     "legendFormat": "50th percentile (avg)"
    },
    {
     "expr": "max(histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\"}[$__rate_interval]))))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(histogram_quantile(0.999, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\"}[$__rate_interval]))))",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  { "title": "KPIs - Query Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(n1ql_requests{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(n1ql_request_time{cluster=\"$cluster\"}[$__rate_interval]) / increase(n1ql_requests{cluster=\"$cluster\"}[$__rate_interval]) / 1000000\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}